### PR TITLE
set tools.system.package_manager config

### PR DESCRIPTION
**Pull request by ericLemanissier**

### CODE REVIEW

**Comment by qchateau** [comment]
Looking good but I don't know these settings. Could you explain what the defaults are, what this PR changes and why it's necessary?

My only worry would be that it makes sudo access a requirement for this bot ?

**Comment by ericLemanissier** [comment]
since https://github.com/conan-io/conan-center-index/commit/9b431d4ae880f8f3b9a9b2660f6aed9399c9f4f7, xorg recipe uses the new system package tools, so the configuration needed to enable actual system package setup has to be updated, as per https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#methods-available-for-system-package-manager-tools.
You can see on the same page that sudo is disabled by default, whereas it was enabled by default with the previous system package tools (https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-sudo)

**Comment by qchateau** [comment]
Thanks 👍

**Comment by ericLemanissier** [comment]
woopsie, it now fails https://github.com/qchateau/conan-center-bot/runs/7855549099?check_suite_focus=true#step:13:6137
I'm on it

**Pull request merged**
